FROM registry1.dso.mil/ironbank/big-bang/base:2.1.0

USER root

RUN mkdir -p /var/cache/dnf
RUN microdnf update -y

RUN microdnf install -y java-11-openjdk-headless \
 && microdnf install -y nmap-ncat \
 && microdnf install -y bind-utils \
 && microdnf install -y openssl-libs \
 && microdnf install -y tar \
 && microdnf install -y gzip

#install micro instead of VIM, it has less CVEs
RUN cd /home/base && curl https://getmic.ro | bash
RUN mv /home/base/micro /usr/bin/micro
RUN cd /home/base

RUN mkdir -p /home/base/.local/bin
RUN chown -R base:base /home/base/.local

COPY --chown=base --chmod=755 ./kcat-1.7.1/kcat.amd64 /usr/bin/kcat
COPY --chown=base --chmod=755 ./helm-3.16.4/helm.amd64 /usr/bin/helm
COPY --chown=base --chmod=755 ./openshift-client/oc.tar.gz /home/base/.
RUN tar -zxvf /home/base/oc.tar.gz
RUN rm /home/base/oc.tar.gz
RUN mv oc /usr/bin/oc
RUN chown base:base /usr/bin/oc

RUN microdnf remove -y gzip
RUN microdnf remove -y tar
RUN rm -rf /var/cache/dnf

WORKDIR /home/base

COPY --chown=base --chmod=755 ./kafka_2.13-3.8.1 /home/base/kafka_2.13-3.8.1/.
COPY --chown=base --chmod=755 ./ksqldb-cli-7.8.0 /home/base/ksqldb-cli-7.8.0/.

ENV PATH="${PATH}:/home/base/kafka_2.13-3.8.1/bin:/home/base/ksqldb-cli-7.8.0/bin"

USER base

#used to keep pod alive in k8s deployment
CMD ["sh", "-c", "tail -f /dev/null"]

